name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 'Install changeset'
        run: 'pnpm install @changesets/cli --global'
      
      - name: 'Install deps'
        run: 'pnpm install'

      - name: Determine if publish is needed
        id: determine_publish
        uses: ./.github/actions/determine-changeset-publish

      - name: Show has determine_publish action publish
        if: steps.determine_publish.outputs.action == 'publish'
        run: echo "publish!"

      - name: Show determine_publish action pr
        if: steps.determine_publish.outputs.action == 'pr'
        run: echo "pr!"

      - name: Show determine_publish action none
        if: steps.determine_publish.outputs.action == 'none'
        run: echo "do nothing!"

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          commitMode: github-api
          version: bash ./changeset-version.sh
          publish: bash ./changeset-publish.sh